# # # version: '3.8'

# # services:
# #   mydotnetapp:
# #     build: .
# #     container_name: my_dotnet_app_container
# #     environment:
# #       - ASPNETCORE_ENVIRONMENT=Development
# #     volumes:
# #       - .:/app
# #     ports:
# #       - "5000:80"
# version: '3.8'

# services:
#   mydotnetapp:
#     build: .
#     container_name: my_dotnet_app_container
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#     volumes:
#       - .:/app
#     ports:
#       - "5000:80"
version: '3.8'

services:
  mydotnetapp:
    build: .
    container_name: my_dotnet_app_container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/app
    ports:
      - "5000:80"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_dotnet_app_tests
    command: ["dotnet", "test", "--logger:trx;LogFileName=test_results.trx"]
    volumes:
      - .:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
